services:
  openplc:
    image: tuttas/openplc_v3:latest
    container_name: independent_openplc_brain
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "502:502"
    networks:
      plc_isolated_net:
        ipv4_address: 10.20.20.100

networks:
  plc_isolated_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.20.0/24
          gateway: 10.20.20.1

